### PR TITLE
Added the script for numpy

### PR DESCRIPTION
**Pull request by midopooler**

### CODE REVIEW

**Comment by shivaylamba** [comment]
Thanks for the PR @midopooler

**Comment by midopooler** [comment]
Welcome @shivaylamba for the opportunity

**Review by shivaylamba — CHANGES_REQUESTED** [review]
Upon checking the PR content, I see that you have simply copied the one of the previous PR. This is not a good practice @midopooler 
image

**Comment by shivaylamba** [comment]
I am tagging @raghavdhingra who should your PR

**Comment by midopooler** [comment]
Yeah @raghavdhingra

**Comment by shivaylamba** [comment]
@midopooler why do you copy other's work. You are an Unity SDE

**Comment by midopooler** [comment]
I didn't copied anything?

**Comment by midopooler** [comment]
I didn't copied anything?

**Comment by shivaylamba** [comment]
thnx

**Pull request closed without merging**
